[Misc] Make the repo REUSE compliant (#6474)
* Add license information

* Add reuse lint workflow

* Add snippets for spdx

* fix: minor wording adjustments and typo fixes

Co-authored-by: NightKev <34855794+DayKev@users.noreply.github.com>

* chore: add FileContributor attributions for Bertie

Co-authored-by: Bertie690 <136088738+Bertie690@users.noreply.github.com>

* begin licensing some audio assets

* Add pokemon reborn sound affect attribution

* Annotate Leavannite's section

* Add more licensing info

* Add license info to license files ._.

* Move ps1 files out of public

* Add license for animation jsons

* Add license for bat scripts in public

* Update licensing in scripts

* Fix typo in license ref

* Fix AGPL-3.0-or-later

* Add license info to typedoc.config.js

* Add MIT license for snippets

* chore: update license info for files in scripts

* chore: update license info

* chore: update license info

* chore: update license info

* Remove licenses used only by public before linting with reuse

* Add license info to new files added by docker PR

* chore: apply biome

* fix: add back linting workflow lost during merge

* Add attribution based on Hanniel's information

* Add attribution based on Officer Porkchop and Green Ninja's information

* add attribution to unicorn_power for reshiram/zekrom/kyurem epic variant

* Fixup minor typo

* Adjust sprite test to not think REUSE.toml is a sprite json

* Add missing continue-on-error to workflow

* fix: address kev's comments from code review

* docs: minor touchups

---------

Co-authored-by: NightKev <34855794+DayKev@users.noreply.github.com>
Co-authored-by: Bertie690 <136088738+Bertie690@users.noreply.github.com>

diff --git a/.github/workflows/linting.yml b/.github/workflows/linting.yml
--- a/.github/workflows/linting.yml
+++ b/.github/workflows/linting.yml
@@ -6,13 +6,13 @@ on:
       - main
       - beta
       - release
-      - 'hotfix*'
+      - "hotfix*"
   pull_request:
     branches:
       - main
       - beta
       - release
-      - 'hotfix*'
+      - "hotfix*"
   merge_group:
     types: [checks_requested]
 
@@ -64,46 +64,59 @@ jobs:
         id: typecheck-scripts
         continue-on-error: true
 
+      # NOTE: This step *must* run as the last linter; it deletes files in `public/`
+      # Files in public/ do not yet have full licensing information, so remove them before checking for reuse compliance
+      - name: Prepare for reuse compliance
+        run: rm -rf public/* LICENSES/LicenseRef-*
+
+      - name: Check for reuse compliance
+        id: reuse-lint
+        uses: fsfe/reuse-action@v5
+        continue-on-error: true
+
       - name: Evaluate for Errors
         env:
           BIOME_LINT_OUTCOME: ${{ steps.biome_lint.outcome }}
           DEPCRUISE_OUTCOME: ${{ steps.depcruise.outcome }}
           TYPECHECK_OUTCOME: ${{ steps.typecheck.outcome }}
           TYPECHECK_SCRIPTS_OUTCOME: ${{ steps.typecheck-scripts.outcome }}
+          REUSE_OUTCOME: ${{ steps.reuse-lint.outcome }}
         run: |
-            # Check for Errors
+          # Check for Errors
 
-            # Make text red.
-            red () {
-              printf "\e[31m%s\e[0m" "$1"
-            }
+          # Make text red.
+          red () {
+            printf "\e[31m%s\e[0m" "$1"
+          }
 
-            # Make text green.
-            green () {
-              printf "\e[32m%s\e[0m" "$1"
-            }
+          # Make text green.
+          green () {
+            printf "\e[32m%s\e[0m" "$1"
+          }
 
-            print_result() {
-              local name=$1
-              local outcome=$2
-              if [ "$outcome" == "success" ]; then
-                printf "$(green "✅ $name: $outcome")\n"
-              else
-                printf "$(red "❌ $name: $outcome")\n"
-              fi
-            }
-
-            print_result "Biome" "$BIOME_LINT_OUTCOME"
-            print_result "Depcruise" "$DEPCRUISE_OUTCOME"
-            print_result "Typecheck" "$TYPECHECK_OUTCOME"
-            print_result "Typecheck scripts" "$TYPECHECK_SCRIPTS_OUTCOME"
-
-            if [[ "$BIOME_LINT_OUTCOME" != "success" || \
-              "$DEPCRUISE_OUTCOME" != "success" || \
-              "$TYPECHECK_OUTCOME" != "success" || \
-              "$TYPECHECK_SCRIPTS_OUTCOME" != "success" ]]; then
-              printf "$(red "❌ One or more checks failed!")\n" >&2
-              exit 1
+          print_result() {
+            local name=$1
+            local outcome=$2
+            if [ "$outcome" == "success" ]; then
+              printf "$(green "✅ $name: $outcome")\n"
+            else
+              printf "$(red "❌ $name: $outcome")\n"
             fi
+          }
 
-            printf "$(green "✅ All checks passed!")\n"
+          print_result "Biome" "$BIOME_LINT_OUTCOME"
+          print_result "Depcruise" "$DEPCRUISE_OUTCOME"
+          print_result "Typecheck" "$TYPECHECK_OUTCOME"
+          print_result "Typecheck scripts" "$TYPECHECK_SCRIPTS_OUTCOME"
+          print_result "Reuse Compliance" "$REUSE_OUTCOME"
+
+          if [[ "$BIOME_LINT_OUTCOME" != "success" || \
+            "$DEPCRUISE_OUTCOME" != "success" || \
+            "$TYPECHECK_OUTCOME" != "success" || \
+            "$TYPECHECK_SCRIPTS_OUTCOME" != "success" || \
+            "$REUSE_OUTCOME" != "success" ]]; then
+            printf "$(red "❌ One or more checks failed!")\n" >&2
+            exit 1
+          fi
+
+          printf "$(green "✅ All checks passed!")\n"
